kind: Service                             
apiVersion: v1
metadata:
  name: mrburnwal-DevOps
  labels:
    app: mrburnwal-DevOps
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: mrburnwal-DevOps                   
  type: LoadBalancer 